title = "Chickynoid"
gitRepoUrl = "https://github.com/MrChickenRocket/chickynoid"

gitSourceBranch = "main"
changelog = true
classOrder = []

[footer]
style = "dark"
copyright = "Copyright © 2021 MrChickenRocket. Built with Moonwave and Docusaurus"
